// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Test.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class AgregarNuevoDiagnosticoFeature : object, Xunit.IClassFixture<AgregarNuevoDiagnosticoFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "AgregarNuevoDiagnostico.feature"
#line hidden
        
        public AgregarNuevoDiagnosticoFeature(AgregarNuevoDiagnosticoFeature.FixtureData fixtureData, Test_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Agregar nuevo diagnostico", "Como medico\r\nQuiero agregar un nuevo diagnostico\r\nPara registrarlo en la historia" +
                    " clinica del paciente y poder ingresar una evolucion", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="El medico agrega un nuevo diagnostico a lista de diagnosticos del paciente")]
        [Xunit.TraitAttribute("FeatureTitle", "Agregar nuevo diagnostico")]
        [Xunit.TraitAttribute("Description", "El medico agrega un nuevo diagnostico a lista de diagnosticos del paciente")]
        [Xunit.TraitAttribute("Category", "tag1")]
        public void ElMedicoAgregaUnNuevoDiagnosticoAListaDeDiagnosticosDelPaciente()
        {
            string[] tagsOfScenario = new string[] {
                    "tag1"};
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("El medico agrega un nuevo diagnostico a lista de diagnosticos del paciente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Id",
                            "Descripcion"});
                table1.AddRow(new string[] {
                            "1",
                            "Angina"});
                table1.AddRow(new string[] {
                            "2",
                            "Dengue"});
                table1.AddRow(new string[] {
                            "3",
                            "Covid"});
#line 9
 testRunner.Given("el listado de diagnosticos del paciente con dni \"44105560\"", ((string)(null)), table1, "Given ");
#line hidden
#line 14
 testRunner.When("el medico agrega el diagnostico \"Coartacion Aortica\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 15
 testRunner.Then("el diagnostico ingresado es incorporado en la lista de diagnosticos de la histori" +
                        "a clinica del paciente.", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                AgregarNuevoDiagnosticoFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                AgregarNuevoDiagnosticoFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
